name: Tweet Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Call the Twitter Bot API
        run: curl -X GET "https://html-editor-pro-bot.vercel.app/api/tweet"
        
